### ISSUE TITLE
External runtime masking Tempfile exceptions

### ISSUE THREAD

**Issue by darrenboyd** [sstephenson/execjs#113]
The ensure logic In ```ExecJS::ExternalRuntime#compile_to_tempfile``` is masking exceptions coming from Tempfile.

Basically, this code....

```ruby
  def compile_to_tempfile(source)
    tempfile = Tempfile.open(['execjs', '.js'])
    tempfile.write compile(source)
    tempfile.close
    yield tempfile
  ensure
    tempfile.close!
  end
```

should look like...

```ruby
  def compile_to_tempfile(source)
    tempfile = Tempfile.open(['execjs', '.js'])
    tempfile.write compile(source)
    tempfile.close
    yield tempfile
  ensure
    tempfile.close! if tempfile
  end
```

If ```Tempfile.open``` fails, it's likely there is no Tempfile.  This happens when Tmpdir has run out of disk space, or the current user doesn't have write access.

The error we get with the current version is...

```
  NoMethodError: undefined method `close!' for nil:NilClass
```

I'd be glad to write a patch, but I'm not entirely sure how to setup the test properly.

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.
