### ISSUE TITLE
I have got an error when I run this command

### ISSUE THREAD

**Issue by gpkarthick** [sstephenson/execjs#120]
karthik@dev1:~/Desktop/webgpk$ rails s
/var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails_generator/options.rb:32:in `default_options': undefined method `write_inheritable_attribute' for Rails::Generator::Base:Class (NoMethodError)
	from /var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails_generator/base.rb:90:in `<class:Base>'
	from /var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails_generator/base.rb:85:in `<module:Generator>'
	from /var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails_generator/base.rb:48:in `<module:Rails>'
	from /var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails_generator/base.rb:6:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails_generator.rb:34:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/rails-2.3.5/bin/rails:14:in `<top (required)>'
	from /usr/local/bin/rails:23:in `load'
	from /usr/local/bin/rails:23:in `<main>'

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.
