### ISSUE TITLE
JSON::GeneratorError after moving from 1.4.0 to 2.0.x

### ISSUE THREAD

**Issue by nickcoyne** [sstephenson/execjs#132]
Using this in a js.coffee erb template

```coffeescript
$("#stats").replaceWith("<%= escape_javascript(render @template) %>")
```

now causes this error

    JSON::GeneratorError - only generation of JSON objects or arrays allowed:
      /Users/Nick/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/json/common.rb:216:in `generate'
      /Users/Nick/.rbenv/versions/1.9.3-p327/lib/ruby/1.9.1/json/common.rb:345:in `dump'
      execjs (2.0.0) lib/execjs/external_runtime.rb:19:in `eval'
      execjs (2.0.0) lib/execjs/external_runtime.rb:33:in `call'
      coffee-script (2.2.0) lib/coffee_script.rb:57:in `compile'
      app/views/admin/stats/stats.js.coffee:1:in `_app_views_admin_stats_stats_js_coffee___1014294459951170846_70216695895960'

This worked just fine with 1.4.0 Should a different approach now be used?

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.
