### ISSUE TITLE
extract_result: SyntaxError

### ISSUE THREAD

**Issue by AllThatIsTheCase** [sstephenson/execjs#135]
(execjs 2.0.2, nodejs 0.10.20)

When I run this script:

#!/usr/bin/env ruby
require "execjs"
require "open-uri"
require 'pp'
source = ''
source += open('https://www.dropbox.com/static/api/dropbox-datastores-1.0-latest.js').read
source += "'red yellow blue'.split(' ')"
pp ExecJS.eval(source)

I get this error

/home/emile/.rvm/gems/ruby-1.9.3-p448@zotero-pdfscanner/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:66:in `extract_result': SyntaxError: Unexpected token ; (ExecJS::RuntimeError)
        from /home/emile/.rvm/gems/ruby-1.9.3-p448@zotero-pdfscanner/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:28:in `block in exec'
        from /home/emile/.rvm/gems/ruby-1.9.3-p448@zotero-pdfscanner/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:41:in `compile_to_tempfile'
        from /home/emile/.rvm/gems/ruby-1.9.3-p448@zotero-pdfscanner/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:27:in `exec'
        from /home/emile/.rvm/gems/ruby-1.9.3-p448@zotero-pdfscanner/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:19:in `eval'
        from /home/emile/.rvm/gems/ruby-1.9.3-p448@zotero-pdfscanner/gems/execjs-2.0.2/lib/execjs/runtime.rb:40:in `eval'
        from /home/emile/.rvm/gems/ruby-1.9.3-p448@zotero-pdfscanner/gems/execjs-2.0.2/lib/execjs/module.rb:23:in `eval'

Running the script directly in nodejs yields no errors.

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.
