### ISSUE TITLE
runtimes module has hard coded encoding option

### ISSUE THREAD

**Issue by gykpro** [sstephenson/execjs#139]
in runtimes.rb:
```
Node = ExternalRuntime.new(
      :name        => "Node.js (V8)",
      :command     => ["nodejs", "node"],
      :runner_path => ExecJS.root + "/support/node_runner.js",
      :encoding    => 'UTF-8'
    )
```
When I would like to serve a non-utf8 encoded javascript file in dev environment, seems I have no way to specify the encoding.

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.
