### ISSUE TITLE
NoMethodError: undefined method `Locker' for V8::C:Module

### ISSUE THREAD

**Issue by danschultzer** [sstephenson/execjs#142]
For some reason execjs (and maybe rubyracer?) doesn't work anymore. I'm on Mac OS X Mavericks using RubyStack.

I have removed and install the following libraries with no effect: libv8, therubyracer, execjs. I have tried to change version of execjs installed (2, and 1.4). Nothing seems to work.

What can I do?

``NoMethodError: undefined method `Locker' for V8::C:Module
	from /Applications/rubystack-2.0.0-9/ruby/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `lock'
	from /Applications/rubystack-2.0.0-9/ruby/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:9:in `initialize'
	from /Applications/rubystack-2.0.0-9/ruby/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/runtime.rb:44:in `new'
	from /Applications/rubystack-2.0.0-9/ruby/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/runtime.rb:44:in `compile'
	from /Applications/rubystack-2.0.0-9/ruby/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/module.rb:27:in `compile'``

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.
