### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by willcosgrove** [sstephenson/execjs#175]
I noticed on HackerNews that [io.js](https://iojs.org) just hit 1.0.  My first thought was wondering if I could use it with Rails.  But after installing I noticed that it symlinks itself in place of the node binary.  So ExecJS should be able to use it without knowing that it exists.

Even so, does anyone think it would be good to add io.js as a separate runtime?  If so, I'm more than happy to submit a PR :smile:

**Comment by josh** [comment]
io.js installs a `node` binary, so it will automatically work.
