### ISSUE TITLE
Error message: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)

### ISSUE THREAD

**Issue by javyliu** [sstephenson/execjs#77]
I have install the node.js and  when i use "rails s",it's ok,but when I use passenger+nginx get the following error:

These are the possible causes:
There may be a syntax error in the application's code. Please check for such errors and fix them.
A required library may not installed. Please install all libraries that this application requires.
The application may not be properly configured. Please check whether all configuration files are written correctly, fix any incorrect configurations, and restart this application.
A service that the application relies on (such as the database server or the Ferret search engine server) may not have been started. Please start that service.
Further information about the error may have been written to the application's log file. Please check it in order to analyse the problem.
Error message:
Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
Exception class:
PhusionPassenger::UnknownError
Application root:
/data1/web/itangyi
Backtrace:
# File    Line    Location

0   /home/itangyi/.rvm/gems/ruby-1.9.3-p125@rails3_2/gems/execjs-1.3.0/lib/execjs/runtimes.rb   50  in `autodetect'
1   /home/itangyi/.rvm/gems/ruby-1.9.3-p125@rails3_2/gems/execjs-1.3.0/lib/execjs.rb    5   in`'
2   /home/itangyi/.rvm/gems/ruby-1.9.3-p125@rails3_2/gems/execjs-1.3.0/lib/execjs.rb    4   in `'
3   /home/itangyi/.rvm/gems/ruby-1.9.3-p125@rails3_2/gems/coffee-script-2.2.0/lib/coffee_script.rb  1   in`require'
4   /home/itangyi/.rvm/gems/ruby-1.9.3-p125@rails3_2/gems/coffee-script-2.2.0/lib/coffee_script.rb  1   in `'
5   /home/itangyi/.rvm/gems/ruby-1.9.3-p125@rails3_2/gems/coffee-script-2.2.0/lib/coffee-script.rb  1   in`require'
6   /home/itangyi/.rvm/gems/ruby-1.9.3-p125@rails3_2/gems/coffee-script-2.2.0/lib/coffee-script.rb  1   in `'

somebody know why?

**Comment by sobrinho** [comment]
I'm having the same issue on vagrant using nginx + passenger.

But it's okay on rails console:

```
(main) normal> ExecJS.runtime
=> #<ExecJS::ExternalRuntime:0x00000005ed0da0 @name="Node.js (V8)", @command=["nodejs", "node"], @runner_path="/vagrant/app/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/support/node_runner.js", @test_args=nil, @test_match=nil, @encoding="UTF-8", @deprecated=false, @binary="nodejs">
```

Maybe ExecJS is not detecting the nodejs binary but it's present on `/usr/bin/node` and `/usr/bin/nodejs`.

There is any way to force the binary path on ExecJS?

**Comment by bleakwood** [comment]
Try adding env PATH; in nginx.conf file. That worked for me.

**Comment by sobrinho** [comment]
I ended using a trick of passenger, create `/usr/local/bin/ruby2.1-for-passenger ` and put this:

```
#!/bin/sh
export PATH=/usr/local/bin:/usr/bin:/bin

exec "/usr/bin/ruby2.1" "$@"
```

It's kind of hidden trick posted [here](http://blog.phusion.nl/2008/12/16/passing-environment-variables-to-ruby-from-phusion-passenger/) by Phusion guys.

**Comment by aar0nr** [comment]
I had the same problem. Node was installed, but when running rails via phusion passenger, the runtime wasn't being detected. I added ```env PATH;``` to the ```/etc/nginx/nginx.conf``` file and it worked as @bleakwood suggested.
