### ISSUE TITLE
CSCRIPT.EXE doesn't work out-of-the-box on Windows 8 Consumer Preview

### ISSUE THREAD

**Issue by jediry** [sstephenson/execjs#81]
Getting Rails to work on Windows 8 CP has been challenging...the biggest hurdle has been that ExecJS isn't working. I finally tracked it down to something related to the character encoding: if I remove the //U flag to cscript.exe and change the output encoding to UTF-8 in runtimes.rb, it works again. Not sure whether this is a problem with Ruby on Win8, or with cscript.exe on Win8.

**Comment by javadKarbasian** [comment]
it doesn't work for me with version 2.4 execjs...

**Comment by zhongyi-tong** [comment]
doesn't work for version 2.4 execjs +1

**Comment by rodrigoargumedo** [comment]
+1

**Comment by DSAMPAT** [comment]
For windows users, this may work. There is a problem with coffee-script-source >1.9.0 running on windows.

It seems you have to add this to your gemfile:

gem 'coffee-script-source', '1.8.0'

then do

bundle update coffee-script-source

**Comment by rodrigoargumedo** [comment]
Or you could do `gem update --system` for the latest version of RubyGems and reinstall execjs? I tried this and it worked like a charm.

**Comment by DSAMPAT** [comment]
@rodrigoargumedo I tried all the above options, and also mixed up a few combinations of them, till I found this http://stackoverflow.com/questions/28241981/rails-4-execjsprogramerror-in-pageswelcome and had done multiple system gem updates and bundle installs and updates.

I reverted all my trials and downgraded my coffee-script-source and it works. Posting here to help out anyone else, who may have a similar issue.

Updating files in vendor/cache
- coffee-script-source-1.8.0.gem
  Removing outdated .gem files from vendor/cache
- coffee-script-source-1.9.1.1.gem
  Bundle updated!

**Comment by rodrigoargumedo** [comment]
@DSAMPAT I did a fresh reinstall with 2.1.6 and ExecJS works fine as it should expect to behave with a single `bundle install`. Earlier versions gave the same exact error when ExecJS was incorrectly parsing the wrong thing. Reverting to 1.8.0 works if when working previous versions of Ruby.

**Comment by DSAMPAT** [comment]
@rodrigoargumedo Unless we compare bundle show we wont know for sure what other differences we may have as our apps may have other gems or dependencies that could use ExecJS as well.

$ gem -v
2.4.8

$ gem update --system
Latest version currently installed. Aborting.

$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]

$ rails -v
Rails 4.2.3

Like I said, Posting here to help out anyone else, who may have a similar issue.

**Comment by codelearner777** [comment]
Hello,

I am having the same problem.
I am new into programming so my needs and the web I build might not influence heavily with this problem. But still, I can not run this line properly.

> <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %>

 so far, I just delete this line in application.html.erb so I can follow some tutorials.

> <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

could some one help me?

my setup is on 
Win 8.1
![image](https://cloud.githubusercontent.com/assets/14092572/10870577/be3df64a-8100-11e5-9312-e75aa2585a95.png)
![image](https://cloud.githubusercontent.com/assets/14092572/10870580/d4b635ea-8100-11e5-839b-bf09e74d1e7f.png)

editing jscript.rb does not solve the problem

> JScript = ExternalRuntime.new(
>   :name        => "JScript",
>  :command     => "cscript //E:jscript //Nologo",
>  :runner_path => ExecJS.root + "/support/jscript_runner.js",
>    :encoding    => 'UTF-8' # CScript with //U returns UTF-16LE

**Comment by RichIsOnRails** [comment]
Just install node.js.  also see
https://richonrails.com/articles/ruby-2-2-on-windows for more info on
Rails/Windows.

**Comment by codelearner777** [comment]
@RichIsOnRails , yupp...I installed node.JS and it works! Thanks!

**Comment by Bassmint123** [comment]
UPDATE: Since Windows 10 with Rails 5.0.0 and Ruby 2.3 has not been mentioned on this thread:
1. On Win10 I got the same error message as jaeezzy above.
2. I did the installation of node.js with no other changes and it runs fine.

**Comment by RichIsOnRails** [comment]
@Bassmint123 yes, these days you basically have to install Node.js.  There aren't really any easy alternatives unless you use WSL.
