### ISSUE TITLE
Feature request: we need debug facility e.g. console.log

### ISSUE THREAD

**Issue by stereobooster** [sstephenson/execjs#91]
[CommoJS Console](http://wiki.commonjs.org/wiki/Console) fits best. Any JS developer is familiar with it.

Additionaly it will solve bug on the node.js:

``` javascript
if (typeof console !== "undefined" && console.log) {
  console.log('foo bar');
}
```

**Comment by habibalamin** [comment]
I'm with you, @stereobooster. This is a glaring omission. If you fork it, I'd use your fork for my next project.
